version: "3"

services:
    web:
        #build: .
        image: localhost:2005/minecraft-server-status:latest
        ports:
            - "2001:8080"
        restart: "unless-stopped"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "128M"
                reservations:
                    cpus: "0.1"
                    memory: "32M"
